config/routes.rb
Rails.application.routes.draw do

  root 'publico_articulos#index'

  get 'publico_articulos/show'

  get 'categorias/:id', to: 'publico_articulos#articulos_categoria', as: 'articulos_categoria'

  get 'articulos/:url', to: 'publico_articulos#show', as: 'articulos_show'

  devise_for :users

  resources :cita
  get 'citass', to: 'citas#nuevo', as: 'citass'
  post 'create_cita', to: 'citas#create_cita' , as: 'create_cita'

  resources :anuncios

  resources :comentarios
  post 'create_comentario', to: 'publico_articulos#create_comentario' , as: 'create_comentario'

  resources :categoria

  resources :articulos

end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
  belongs_to :articulo
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  before_action :set_comentario, only: [:show, :edit, :update, :destroy]

  # GET /comentarios
  # GET /comentarios.json
  def index
    @comentarios = Comentario.all
  end

  # GET /comentarios/1
  # GET /comentarios/1.json
  def show
  end

  # GET /comentarios/new
  def new
    @comentario = Comentario.new
  end

  # GET /comentarios/1/edit
  def edit
  end

  # POST /comentarios
  # POST /comentarios.json
  def create
    @comentario = Comentario.new(comentario_params)

    respond_to do |format|
      if @comentario.save
        format.html { redirect_to @comentario, notice: 'Comentario was successfully created.' }
        format.json { render :show, status: :created, location: @comentario }
      else
        format.html { render :new }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comentarios/1
  # PATCH/PUT /comentarios/1.json
  def update
    respond_to do |format|
      if @comentario.update(comentario_params)
        format.html { redirect_to @comentario, notice: 'Comentario was successfully updated.' }
        format.json { render :show, status: :ok, location: @comentario }
      else
        format.html { render :edit }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comentarios/1
  # DELETE /comentarios/1.json
  def destroy
    @comentario.destroy
    respond_to do |format|
      format.html { redirect_to comentarios_url, notice: 'Comentario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comentario
      @comentario = Comentario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comentario_params
      params.require(:comentario).permit(:nombre, :contenido)
    end
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/views/comentarios/_form.html.erb
<%= form_for(@comentario) do |f| %>
  <% if @comentario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comentario.errors.count, "error") %> prohibited this comentario from being saved:</h2>

      <ul>
      <% @comentario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre, Class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :contenido %><br>
    <%= f.text_area :contenido, Class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-default' %>
  </div>
<% end %>

app/views/comentarios/edit.html.erb
<h1>Editar Comentario</h1>

<%= render 'form' %>

<%= link_to 'Show', @comentario %> |
<%= link_to 'Volver', comentarios_path %>

app/views/comentarios/index.html.erb
<h1>Comentarios</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Contenido</th>
      <th>Articulo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comentarios.each do |comentario| %>
      <tr>
        <td><%= comentario.nombre %></td>
        <td><%= comentario.contenido %></td>
        <td><%= comentario.articulo.titulo  %></td>
        <td><%= link_to 'Editar', edit_comentario_path(comentario), class: 'btn btn-default' %></td>
        <td><%= link_to 'Eliminar', comentario, method: :delete, data: { confirm: 'Estas Seguro?' }, class: 'btn btn-default' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/comentarios/new.html.erb
<h1>New comentario</h1>

<%= render 'form' %>

<%= link_to 'Back', comentarios_path %>

app/views/comentarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @comentario.nombre %>
</p>

<p>
  <strong>Contenido:</strong>
  <%= @comentario.contenido %>
</p>

<%= link_to 'Edit', edit_comentario_path(@comentario) %> |
<%= link_to 'Back', comentarios_path %>