config/routes.rb
Rails.application.routes.draw do

  root 'publico_articulos#index'

  get 'publico_articulos/show'

  get 'categorias/:id', to: 'publico_articulos#articulos_categoria', as: 'articulos_categoria'

  get 'articulos/:url', to: 'publico_articulos#show', as: 'articulos_show'

  devise_for :users

  resources :cita
  get 'citass', to: 'citas#nuevo', as: 'citass'
  post 'create_cita', to: 'citas#create_cita' , as: 'create_cita'

  resources :anuncios

  resources :comentarios
  post 'create_comentario', to: 'publico_articulos#create_comentario' , as: 'create_comentario'

  resources :categoria

  resources :articulos

end

app/models/anuncio.rb
class Anuncio < ActiveRecord::Base
end

app/controllers/anuncios_controller.rb
class AnunciosController < ApplicationController
  before_action :set_anuncio, only: [:show, :edit, :update, :destroy]

  # GET /anuncios
  # GET /anuncios.json
  def index
    @anuncios = Anuncio.all
  end

  # GET /anuncios/1
  # GET /anuncios/1.json
  def show
  end

  # GET /anuncios/new
  def new
    @anuncio = Anuncio.new
  end

  # GET /anuncios/1/edit
  def edit
  end

  # POST /anuncios
  # POST /anuncios.json
  def create
    @anuncio = Anuncio.new(anuncio_params)

    respond_to do |format|
      if @anuncio.save
        format.html { redirect_to @anuncio, notice: 'Anuncio was successfully created.' }
        format.json { render :show, status: :created, location: @anuncio }
      else
        format.html { render :new }
        format.json { render json: @anuncio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /anuncios/1
  # PATCH/PUT /anuncios/1.json
  def update
    respond_to do |format|
      if @anuncio.update(anuncio_params)
        format.html { redirect_to @anuncio, notice: 'Anuncio was successfully updated.' }
        format.json { render :show, status: :ok, location: @anuncio }
      else
        format.html { render :edit }
        format.json { render json: @anuncio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /anuncios/1
  # DELETE /anuncios/1.json
  def destroy
    @anuncio.destroy
    respond_to do |format|
      format.html { redirect_to anuncios_url, notice: 'Anuncio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_anuncio
      @anuncio = Anuncio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def anuncio_params
      params.require(:anuncio).permit(:nombre, :imagen, :link)
    end
end

app/helpers/anuncios_helper.rb
module AnunciosHelper
end

app/views/anuncios/_form.html.erb
<%= form_for(@anuncio) do |f| %>
  <% if @anuncio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@anuncio.errors.count, "error") %> prohibited this anuncio from being saved:</h2>

      <ul>
      <% @anuncio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre, class:'form-control' %>
  </div>
  <div class="field">
    <%= f.label :imagen %><br>
    <%= f.text_field :imagen,class:'form-control' %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link,class:'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit class:'btn btn-default'%>
  </div>
<% end %>

app/views/anuncios/edit.html.erb
<h1>Editing anuncio</h1>

<%= render 'form' %>

<%= link_to 'Ver', @anuncio, class: 'btn btn-default' %> |
<%= link_to 'Regresar', anuncios_path, class: 'btn btn-default' %>

app/views/anuncios/index.html.erb
<h1>Anuncios</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Imagen</th>
      <th>Link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @anuncios.each do |anuncio| %>
      <tr>
        <td><%= anuncio.nombre %></td>
        <td><%= image_tag anuncio.imagen,height: 100 %></td>
        <td><%= anuncio.link %></td>
        <td><%= link_to 'Ver', anuncio, class: 'btn btn-default' %></td>
        <td><%= link_to 'Editar', edit_anuncio_path(anuncio), class: 'btn btn-default' %></td>
        <td><%= link_to 'Eliminar', anuncio, method: :delete, data: { confirm: 'Estas Seguro?' }, class: 'btn btn_default' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Anuncio', new_anuncio_path, class: 'btn btn-default' %>

app/views/anuncios/new.html.erb
<h1>New anuncio</h1>

<%= render 'form' %>

<%= link_to 'Regresar', anuncios_path, class: 'btn btn-default' %>

app/views/anuncios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @anuncio.nombre %>
</p>

<p>
  <strong>Imagen:</strong>
  <%= @anuncio.imagen %>
</p>

<p>
  <strong>Link:</strong>
  <%= @anuncio.link %>
</p>

<%= link_to 'Edit', edit_anuncio_path(@anuncio) %> |
<%= link_to 'Back', anuncios_path %>