config/routes.rb
Rails.application.routes.draw do

  root 'publico_articulos#index'

  get 'publico_articulos/show'

  get 'categorias/:id', to: 'publico_articulos#articulos_categoria', as: 'articulos_categoria'

  get 'articulos/:url', to: 'publico_articulos#show', as: 'articulos_show'

  devise_for :users

  resources :cita
  get 'citass', to: 'citas#nuevo', as: 'citass'
  post 'create_cita', to: 'citas#create_cita' , as: 'create_cita'

  resources :anuncios

  resources :comentarios
  post 'create_comentario', to: 'publico_articulos#create_comentario' , as: 'create_comentario'

  resources :categoria

  resources :articulos

end

app/models/articulo.rb
class Articulo < ActiveRecord::Base
  has_many :comentarios
  belongs_to :categorium
  belongs_to :user

  scope :publicado, -> {where status: true}

end

app/controllers/articulos_controller.rb
class ArticulosController < ApplicationController
  before_action :set_articulo, only: [:show, :edit, :update, :destroy]

  # GET /articulos
  # GET /articulos.json
  def index
    @articulos = Articulo.all
  end

  # GET /articulos/1
  # GET /articulos/1.json
  def show
  end

  # GET /articulos/new
  def new
    @articulo = Articulo.new
  end

  # GET /articulos/1/edit
  def edit
  end

  # POST /articulos
  # POST /articulos.json
  def create
    @articulo = Articulo.new(articulo_params)

    respond_to do |format|
      if @articulo.save
        format.html { redirect_to @articulo, notice: 'Articulo was successfully created.' }
        format.json { render :show, status: :created, location: @articulo }
      else
        format.html { render :new }
        format.json { render json: @articulo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articulos/1
  # PATCH/PUT /articulos/1.json
  def update
    respond_to do |format|
      if @articulo.update(articulo_params)
        format.html { redirect_to @articulo, notice: 'Articulo was successfully updated.' }
        format.json { render :show, status: :ok, location: @articulo }
      else
        format.html { render :edit }
        format.json { render json: @articulo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articulos/1
  # DELETE /articulos/1.json
  def destroy
    @articulo.destroy
    respond_to do |format|
      format.html { redirect_to articulos_url, notice: 'Articulo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_articulo
      @articulo = Articulo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def articulo_params
      params.require(:articulo).permit(:titulo, :contenido, :status, :url, :user_id, :categorium_id)
    end
end

app/helpers/articulos_helper.rb
module ArticulosHelper
end

app/views/articulos/_form.html.erb
<%= form_for(@articulo) do |f| %>
  <% if @articulo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@articulo.errors.count, "error") %> prohibited this articulo from being saved:</h2>

      <ul>
      <% @articulo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo, class:'form-control' %>
  </div>
  <div class="field">
    <%= f.label :contenido %><br>
    <%= f.text_area :contenido, class:'form-control' %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.check_box :status %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url, class:'form-control' %>
  </div>
    <div class="field">
      <%= f.label 'Categoria' %><br>
      <%= f.select :categorium_id, lista_categorias.collect{|c|[c.nombre, c.id]} %>
    </div>
    <%= f.hidden_field :user_id, value: current_user.__id__ %>
  <div class="actions">
    <%= f.submit class:'btn btn-default' %>
  </div>
<% end %>

app/views/articulos/edit.html.erb
<h1>Editar Articulo</h1>

<%= render 'form' %>

<%= link_to 'Ver', @articulo, class: 'btn btn-default' %> |
<%= link_to 'Regresar', articulos_path, class: 'btn btn-default' %>

app/views/articulos/index.html.erb
<h1>Articulos</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Contenido</th>
      <th>Status</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articulos.each do |articulo| %>
      <tr>
        <td><%= articulo.titulo %></td>
        <td><%= articulo.contenido %></td>
        <td><%= articulo.status %></td>
        <td><%= articulo.url %></td>
        <td><%= link_to 'Editar', edit_articulo_path(articulo),class: 'btn btn-default' %></td>
        <td><%= link_to 'Eliminar ', articulo, method: :delete, data: { confirm: 'Estas Seguro?' },class: 'btn btn-default' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Articulo', new_articulo_path, class: 'btn btn-default' %>

app/views/articulos/new.html.erb
<h1>Nuevo Articulo</h1>

<%= render 'form' %>

<%= link_to 'Regresar', articulos_path %>

app/views/articulos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @articulo.titulo %>
</p>

<p>
  <strong>Contenido:</strong>
  <%= @articulo.contenido %>
</p>

<p>
  <strong>Status:</strong>
  <%= @articulo.status %>
</p>

<p>
  <strong>Url:</strong>
  <%= @articulo.url %>
</p>

<%= link_to 'Editar', edit_articulo_path(@articulo) %> |
<%= link_to 'Regresar', articulos_path %>